first workflow with fail

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -14,7 +14,9 @@ jobs:
     runs-on: ubuntu-latest
     steps:
     - name: Failed stop
-      run: echo "I will fail"
+      run: | 
+        echo "I will fail"
+        exit 1
     - name: Say goodbye
       run: echo "Worflow completed....."
 
